language: java
jdk:
- oraclejdk8
script:
  - sbt clean cpd checkstyle test
notifications:
  slack: bringtoafrica:rGSyp0j9xvfP1BQsFOk441pv
  email:
  - sevi_buehler@hotmail.com
  - skurath@hsr.ch
  - lmartine@hsr.ch
  - m2roth@hsr.ch
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/0eb826f4fab05abd2366
deploy:
  provider: heroku
  api_key:
    secure: dzmNmFEnunZgRAVl2RH1uV1AwDlH00/sMUXAL5krGAl18d7CnUDP8KJWmtw7UNXC7dv1VG2qeyfRL8R25QOpnU2p0JFKJA1U1r9wWoCDxSFP8ut6DuIj2AVBNIZ42TtzqJE5lkQzGRkzARn2I7byOIw80FPdlLOffFqGnVi5dG8=
  app: bringtoafrica
  on:
    repo: Sebubu/BringToAfrica
