language: java
jdk:
- oraclejdk8
script:
- sbt clean coverage cpd checkstyle test
after_success: sbt coveralls
notifications:
  slack: bringtoafrica:rGSyp0j9xvfP1BQsFOk441pv
  email:
  - sevi_buehler@hotmail.com
  - skurath@hsr.ch
  - lmartine@hsr.ch
  - m2roth@hsr.ch
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/0eb826f4fab05abd2366
